### ISSUE TITLE
Ever occurred

### ISSUE THREAD

**Issue by bopin2020** [rbmm/DbgView64Crash#1]
In the past, I came across it inside my vmware win11 x64

Bug here:
(1db0.1db4): Access violation - code c0000005 (first chance)
First chance exceptions are reported before any exception handling.
This exception may be expected and handled.
dbgview64+0xac81:
00007ff6`aaacac81 f00fc111        lock xadd dword ptr [rcx],edx ds:00000000`2b6b007c=????????

![image](https://github.com/rbmm/DbgView64Crash/assets/49940777/8e1c27d8-00e9-440c-baf0-6d03acdcb7e8)

I have reversed debugview.exe and dbgv.sys, but I failed to find out why it  touch off access violation like your description.

**Comment by rbmm** [comment]
yes, look for https://github.com/MicrosoftDocs/sysinternals/issues/421

**Comment by rbmm** [comment]
driver map section in user mode process and pass address of mapped section to user mode. this is done via ioctl. however driver wrong pass address of mapped view. instead full pointer ( 8 bytes) it pass only low 4 bytes. as result user mode got wrong address with 0 in high path. for 32bit version this is ok, but 64bit crashed
